bigbluebutton/bbb-app-rooms

app/assets/javascripts/rename.js
app/controllers/rooms_controller.rb
app/helpers/application_helper.rb
app/views/rooms/edit.html.erb
app/views/rooms/index.html.erb
app/views/rooms/index.json.jbuilder
app/views/shared/components/_recording_row.html.erb

Reverts bigbluebutton/bbb-app-rooms#35

Revert "LTI-24: fix for edit recording name and description not working"

---

app/views/shared/components/_recording_row.html.erb

Trying to rename recordings will no longer result in a 401

LTI-58: Fixed authorization for renaming recordings

---

app/controllers/rooms_controller.rb

Option for the meeting to be recorded is enabled by default

LTI-60: Recording is true by default

---

app/assets/javascripts/meetingInfo.js
app/channels/meeting_info_channel.rb
app/controllers/rooms_controller.rb
app/jobs/notify_meeting_watcher_job.rb
app/views/shared/_room.html.erb
lib/bbb_api.rb

When a meeting is in session, the following will be displayed:
- Number of participants in meeting
- Elapsed time since start of meeting

LTI-52: Added missing meeting info

---

app/controllers/rooms_controller.rb
app/views/shared/components/_recording_row.html.erb

If the recordings support protection, then admins/instructors will be given the option to protect/unprotect.

LTI-82: Add support for protected recordings

---

app/jobs/notify_meeting_watcher_job.rb

Fixed broadcast for meeting start / meeting info
To be merged before LTI-93 and LTI-95 (1/3)

LTI-96: Fix for end button functionality for LTI-66

---

Gemfile
Gemfile.lock
app/assets/javascripts/meetingInfo.js
app/assets/javascripts/rooms.js
app/assets/stylesheets/rooms.scss
app/channels/wait_channel.rb
app/controllers/rooms_controller.rb
app/jobs/notify_room_watcher_job.rb
app/views/rooms/meeting_join.html.erb
app/views/shared/_room.html.erb

Firefox was blocking the BBB from opening in another tab because it considered it a pop-up. 
This PR should fix that by introducing a "waiting page"

LTI-101: Fix for firefox blocking BBB as pop-up

---

app/controllers/concerns/bbb_helper.rb
app/views/shared/components/_recording_row.html.erb

Please merge this one **after** LTI-110 (sorting recording formats).

LTI-108: Truncate room description on meeting create

---

app/assets/javascripts/edit.js
app/views/rooms/_form.html.erb

The 'Wait for Moderator' and 'All Moderators' options cannot be active at the same time.

LTI-113: ensure (Wait for mod && all mod) == false

---

app/assets/javascripts/rename.js
app/controllers/rooms_controller.rb

When trying to update a recording name / description a second time, it would not save.
This commit seems to fix that.

LTI-115: Fix to updating recording name error

---

app/controllers/concerns/bbb_helper.rb

LTI-126: Add createTime to join session request

---

app/controllers/concerns/bbb_helper.rb

LTI-132: Include userID as part of join (close #101)

---

app/controllers/concerns/bbb_helper.rb
app/controllers/rooms_controller.rb

on recording update, delete just cache for recordings instead of for entire application

LTI-149: change way cache for recordings is configured

---

app/controllers/concerns/bbb_helper.rb
app/controllers/rooms_controller.rb
app/views/shared/components/_recording_row.html.erb
config/routes.rb

Everytime a request to a protected recording is made, make an API call to retrieve the recording.

LTI-150: do not use cache for protected recordings

---

app/views/rooms/_form.html.erb

Reverts bigbluebutton/bbb-app-rooms#147

Revert "LTI-159: Make room name optional"

---

config/application.rb
dotenv
lib/bbb/credentials.rb

defaults to sha256 if the env. variable isn't set

LTI-160: Make SHA version configurable for checksum

---

app/controllers/rooms_controller.rb
config/environments/production.rb
db/schema.rb

This is a path for the previous LTI-190 PR

LTI-190: Update handler_legacy if passed and nil

---

app/controllers/rooms_controller.rb
config/locales/en.yml

This should fixes the issue with the multi-update on old links

LTI-208c: refactoring applied to legacy so new launches are not allowed

---

config.nginx
dotenv

Added required CD config files (config.nginx) to codebase.

Deployment: Added CD configs.

---

app/views/errors/_error.html.erb
app/views/errors/index.html.erb

LTI-209: Fix error page UI

---

app/channels/wait_channel.rb
app/controllers/concerns/bbb_helper.rb
app/controllers/rooms_controller.rb
app/javascript/packs/meetingInfo.js
app/javascript/packs/rooms.js
app/views/rooms/meeting_join.html.erb

previously viewers were waiting forever on the 'wait' page, even after meeting starts

LTI-186: fix wait for mod 

---

app/models/room.rb
app/views/rooms/_form.html.erb

Only the following settings will show when BIGBLUEBUTTON_RECORDING_ENABLED = false

LTI-238: Hide all recording settings when recording is disabled

---

app/controllers/rooms_controller.rb

Reverts bigbluebutton/bbb-app-rooms#236

Revert "LTI-269: refactoring creation of legacy rooms on launch"

---

app/controllers/concerns/bbb_helper.rb
app/controllers/concerns/broker_helper.rb
app/controllers/rooms_controller.rb
app/javascript/packs/edit.js
app/models/room.rb
app/views/rooms/_form.html.erb
app/views/shared/_room.html.erb
app/views/shared/components/_recording_row.html.erb
config/locales/en.yml
db/migrate/20231102145703_add_columns_to_rooms.rb
db/schema.rb
package.json
spec/factories/room.rb
tailwind.config.js

This PR refers to #260 plus two minor updates added afterwards

LTI-257: Added shared rooms feature

---

app/channels/meeting_info_channel.rb
app/controllers/concerns/bbb_helper.rb
app/controllers/concerns/broker_helper.rb
app/controllers/rooms_controller.rb
app/javascript/packs/meetingInfo.js
app/jobs/notify_meeting_watcher_job.rb
app/jobs/notify_room_watcher_job.rb
app/views/shared/_body.html.erb
app/views/shared/_room.html.erb
spec/concerns/bbb_helper_spec.rb
spec/controllers/rooms_spec.rb

- fixes bug with actioncable/meeting info not working
- fixes bug where users of a shared room can't join the meeting

LTI-257: fix shared rooms bugs

---

app/controllers/concerns/broker_helper.rb
app/models/room.rb

Reverts bigbluebutton/bbb-app-rooms#290

Revert "LTI-321: Pull Default Room Setting Values From Broker (feat)"

---

app/controllers/concerns/bbb_helper.rb
app/controllers/rooms_controller.rb
lib/bbb_app_rooms/user.rb

Added a new pronouns feature. This feature is still not supported by BBB but is set to be in the future.

LTI-352: Implemented pronouns feature

---

app/views/shared/components/_recording_row.html.erb

For cases where the recording format is not video, presentation, or stats

LTI-376: Add a recording playback format catch all

---

app/controllers/concerns/bbb_helper.rb
app/controllers/rooms_controller.rb
app/javascript/packs/rename.js
app/javascript/packs/rooms.js
app/views/shared/_room.html.erb

This feature was implemented by calling all recordings first and counting them, then only displaying a portion at a time. It will have to be updated once the LB/BBB start sending back the totalElements field.

LTI-410: pagination

---

spec/concerns/bbb_helper_spec.rb
spec/controllers/rooms_spec.rb

Faker::IDNumber was depreciated and replaced with IdNumber.

update depreciated faker generator
